select * from customer

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, avg(purchase_amount), discount_applied
from customer
where discount_applied = 'yes' and purchase amount >(select a)
group by customer_id,discount_applied;

-- Q3. Which are the top 5 products with the highest average review rating?

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and sh...

-- Q8. What are the top 3 most purchased products within each category?